<?php

namespace Tests\Feature\Domain\Budget\DataTransferObjects;

use App\Admin\Requests\BudgetMonthRequest;
use Authentication\Models\User;
use Budget\DataTransferObjects\BudgetMonthData;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Route;
use Tests\TestCase;

class BudgetMonthDataTest extends TestCase
{
    use RefreshDatabase;

    public User $user;


    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->user = User::factory()->create();
        $this->actingAs($this->user);
        Route::post('/fakerdoodledoo', function(BudgetMonthRequest $request) {
            $this->validated = BudgetMonthData::fromRequest($request, $this->user);
        });
    }

    /** @test * */
    public function it_implements_arrayable_and_converts_dollars_to_int()
    {
        $this->freezeTime();
        $time = now()->addWeek()->format('Y-m-d');
        $this->post('/fakerdoodledoo', [
            'month' => $time,
            'planned_income' => '500.00',
        ]);

        $this->assertEquals([
            'month' => $time,
            'planned_income' => 50000,
            'user_id' => $this->user->id,
        ], $this->validated->toArray());
    }
}
