<?php

namespace Tests\Feature\Domain\Budget\DataTransferObjects;

use App\Admin\Requests\BudgetTransactionRequest;
use Budget\DataTransferObjects\BudgetTransactionData;
use Illuminate\Support\Facades\Route;
use Tests\TestCase;

class BudgetTransactionDataTest extends TestCase
{
    public BudgetTransactionData $validated;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        Route::post('/myfakeroute3', function(BudgetTransactionRequest $request) {
            $this->validated = BudgetTransactionData::fromRequest($request);
        });
    }

    /** @test * */
    public function it_implements_arrayable_and_converts_variables()
    {
        $date = now()->subWeek()->startOfDay();
        $this->post('/myfakeroute3', [
            'name' => 'My amazing name',
            'amount' => '5',
            'date_purchased' => $date->format('Y-m-d'),
            'budget_item_id' => 1,
        ]);

        $this->assertEquals([
            'name' => 'My amazing name',
            'amount' => 500,
            'date_purchased' => $date,
            'budget_item_id' => 1,
        ], $this->validated->toArray());
    }
}
