<?php

namespace Tests\Feature\Domain\Budget\DataTransferObjects;

use App\Admin\Requests\BudgetItemRequest;
use Budget\DataTransferObjects\BudgetItemData;
use Illuminate\Support\Facades\Route;
use Tests\TestCase;

class BudgetItemDataTest extends TestCase
{
    protected $validated;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        Route::post('/fake-route', function(BudgetItemRequest $request) {
            $this->validated = BudgetItemData::fromRequest($request);
        });
    }

    /** @test * */
    public function it_implements_arrayable_and_converts_dollars_to_int()
    {
        $data = [
            'name' => 'Fake Name',
            'planned_amount' => "23.23",
        ];

        $this->post('/fake-route', [
            'name' => 'Fake Name',
            'planned_amount' => "23.23",
        ]);

        $this->assertEquals([
            'name' => 'Fake Name',
            'planned_amount' => 2323,
        ], $this->validated->toArray());
    }
}
