<?php

namespace Tests\Feature\Domain\Budget\DataTransferObjects;

use App\Admin\Requests\PaycheckRequest;
use Budget\DataTransferObjects\PaycheckData;
use Budget\Models\BudgetMonth;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Route;
use Tests\TestCase;

class PaycheckDataTest extends TestCase
{
    use RefreshDatabase;

    public PaycheckData $validated;
    public BudgetMonth $budget;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->budget = BudgetMonth::factory()->create();
        Route::post('/myfakeroute4', function(PaycheckRequest $request) {
            $this->validated = PaycheckData::fromRequest($request, $this->budget);
        });
    }

    /** @test * */
    public function it_implements_arrayble()
    {
        $date = now()->subWeek()->startOfDay();

        $this->post('myfakeroute4', [
            'amount' => '5',
            'payday' => $date->format('Y-m-d'),
        ]);

        $this->assertEquals([
            'amount' => 500,
            'payday' => $date,
            'budget_month_id' => $this->budget->id,
        ], $this->validated->toArray());
    }
}
